# Generated by Django 4.2.7 on 2023-11-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_attendance_date_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaff',
            name='feedback',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='reply',
            field=models.TextField(verbose_name='Responder'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='reply',
            field=models.TextField(verbose_name='Responder'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='date',
            field=models.CharField(max_length=60, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='date',
            field=models.CharField(max_length=60, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
