# Generated by Django 4.2.7 on 2023-11-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_feedbackstaff_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstaff',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
